import type { contactEvent, providerIdentity } from '@/db/schema'
import type {
	evergreenOfferJourneyCommit,
	evergreenOfferJourneyIntent,
	evergreenOfferJourneyWake,
} from '@/db/evergreen-offer-journey-schema'
import { MySqlDialect } from 'drizzle-orm/mysql-core'
import type { SQL } from 'drizzle-orm'
import {
	semanticCouponId,
	type VerifiedCouponOwnerQuery,
} from './coupon-authority'
import { fixtureEntry, fixtureCommit } from './bounded-readers.fixtures'
import {
	EVERGREEN_OFFER_JOURNEY_COMMIT_FORMAT,
	EVERGREEN_OFFER_JOURNEY_INTENT_FORMAT,
	EVERGREEN_OFFER_JOURNEY_WAKE_FORMAT,
} from './persistence-contract'
import { journeyCommitEvidenceRecord } from './persistence-codec'
import { encodeEvergreenOfferJourneySnapshot } from './restoration'
import {
	parseCouponId,
	parseIsoInstant,
	parseStimulusId,
	parseVerifiedUserId,
	type ParseResult,
} from './primitives'
import type { JourneyLedgerCommit } from './ports'
import {
	emailFingerprint,
	emailTokenHash,
	sessionTokenHash,
	emailTokenLoginEventRow,
	resolveOwnerContact,
	offerClaimEventRow,
	claimSourceReference,
	type EmailTokenLoginObservedPayload,
	type OfferClaimObservedPayload,
} from './verified-owner-evidence'
import type { VerifiedOwnerEvidenceReadStore } from './verified-owner-proof'
import type { EvergreenOfferJourneyTransaction } from './drizzle-ledger'

function value<A>(parsed: ParseResult<A>): A {
	if (!parsed.ok) throw new Error('Invalid synthetic fixture')
	return parsed.value
}
// Synthetic domain history, not auth evidence. Every candidate is generated by
// the real decision engine. MySQL tests commit these candidates through the real
// ledger; offline tests serialize them and emulate only indexed row selection.
export function ownerProofFixture() {
	const entry = fixtureEntry('proof-contact')
	const couponWake = entry.decision.wakeIntents.find(
		(w) => w.purpose.type === 'CouponIssue',
	)
	if (!couponWake) throw new Error('Missing coupon wake')
	const awaiting = fixtureCommit(
		entry.decision.next,
		{
			type: 'WakeDue',
			stimulusId: value(parseStimulusId('proof-coupon-wake')),
			journeyId: entry.decision.next.journeyId,
			wakeId: couponWake.wakeId,
			purpose: couponWake.purpose,
			dueAt: couponWake.dueAt,
		},
		couponWake.dueAt,
	)
	const issueIntent = awaiting.decision.sideEffectIntents.find(
		(i) => i.type === 'IssueCoupon',
	)
	if (!issueIntent || issueIntent.type !== 'IssueCoupon')
		throw new Error('Missing issue intent')
	const coupon = {
		couponId: value(
			parseCouponId(semanticCouponId(issueIntent.idempotencyKey)),
		),
		contactId: issueIntent.contactId,
		issuedAt: issueIntent.issueAt,
		expiresAt: issueIntent.expiresAt,
		terms: issueIntent.terms,
		deadlineTimeZone: issueIntent.deadlineTimeZone,
		binding: { type: 'AwaitingVerifiedUser' as const },
	}
	const pitched = fixtureCommit(
		awaiting.decision.next,
		{
			type: 'CouponIssued',
			stimulusId: value(parseStimulusId('proof-coupon-issued')),
			journeyId: issueIntent.journeyId,
			intentKey: issueIntent.idempotencyKey,
			coupon,
		},
		coupon.issuedAt,
	)
	const secret = 'synthetic-fixture-secret'
	const verifiedAt = '2026-09-10T16:00:00.123Z'
	const loginObserved = '2026-09-10T16:00:01.234Z'
	const claimObserved = '2026-09-10T16:00:02.345Z'
	const committedAt = '2026-09-10T16:00:03.456Z'
	const now = '2026-09-10T17:00:00.000Z'
	const identity: typeof providerIdentity.$inferSelect = {
		id: 'proof-kit-identity',
		contactId: issueIntent.contactId,
		provider: 'kit',
		externalId: 'synthetic-kit-id',
		evidence: {},
		createdAt: new Date(verifiedAt),
		updatedAt: new Date(verifiedAt),
	}
	const login: EmailTokenLoginObservedPayload = {
		version: 1,
		contactId: identity.contactId,
		userId: 'proof-user',
		emailFingerprint: emailFingerprint(secret, 'proof@example.test'),
		verifiedAt,
		sessionTokenHash: sessionTokenHash(secret, 'synthetic-session'),
		tokenHash: emailTokenHash(secret, 'synthetic-token'),
		mechanism: 'auth-email-callback',
		observedAt: loginObserved,
	}
	const claim: OfferClaimObservedPayload = {
		version: 1,
		journeyId: issueIntent.journeyId,
		contactId: identity.contactId,
		verifiedUserId: login.userId,
		attestationEventId: 'proof-login-event',
		sessionTokenHash: login.sessionTokenHash,
		emailFingerprint: login.emailFingerprint,
		verifiedAt,
		observedAt: claimObserved,
	}
	const rows: (typeof contactEvent.$inferSelect)[] = [
		{
			...emailTokenLoginEventRow({
				resolution: resolveOwnerContact(
					[identity.contactId],
					identity.contactId,
				),
				id: claim.attestationEventId,
				identity: { ...identity, provider: 'kit' },
				payload: login,
			}),
			createdAt: new Date(loginObserved),
		},
		{
			...offerClaimEventRow({
				resolution: resolveOwnerContact(
					[identity.contactId],
					identity.contactId,
				),
				id: 'proof-claim-event',
				identity: { ...identity, provider: 'kit' },
				payload: claim,
			}),
			createdAt: new Date(claimObserved),
		},
	]
	const observed = fixtureCommit(
		pitched.decision.next,
		{
			type: 'VerifiedUserObserved',
			stimulusId: value(parseStimulusId('proof-claim-event')),
			journeyId: issueIntent.journeyId,
			verifiedUserId: value(parseVerifiedUserId(login.userId)),
			observedAt: value(parseIsoInstant(claimObserved)),
			sourceReference: claimSourceReference('proof-claim-event'),
		},
		committedAt,
	)
	const candidates = [entry, awaiting, pitched, observed]
	const commits = candidates.map(commitRow)
	const commit = commits[3]!
	const allIntents = candidates.flatMap(intentRows)
	const allWakes = candidates.flatMap(wakeRows)
	// Mirror the two settlements in this history, not an all-Pending fabrication.
	const issuedRow = allIntents.find(
		(row) => row.idempotencyKey === issueIntent.idempotencyKey,
	)!
	issuedRow.status = 'Applied'
	issuedRow.settledByStimulusId = pitched.stimulus.stimulusId
	issuedRow.settledAt = new Date(pitched.decidedAt)
	issuedRow.updatedAt = new Date(pitched.decidedAt)
	const firedWake = allWakes.find((row) => row.wakeId === couponWake.wakeId)!
	firedWake.status = 'Applied'
	firedWake.settledByStimulusId = awaiting.stimulus.stimulusId
	firedWake.settledAt = new Date(awaiting.decidedAt)
	firedWake.updatedAt = new Date(awaiting.decidedAt)
	const intentRow = allIntents.find((row) => row.intentType === 'BindCoupon')!
	const bindIntent = observed.decision.sideEffectIntents.find(
		(i) => i.type === 'BindCoupon',
	)
	if (!bindIntent || bindIntent.type !== 'BindCoupon')
		throw new Error('Missing bind intent')
	const input: VerifiedCouponOwnerQuery = {
		contactId: claim.contactId,
		journeyId: claim.journeyId,
		verifiedUserId: login.userId,
		couponId: coupon.couponId,
		lockedContact: { id: claim.contactId, email: 'proof@example.test' },
		lockedUser: {
			id: login.userId,
			email: 'proof@example.test',
			emailVerified: verifiedAt,
		},
	}
	const calls: string[] = []
	const dialect = new MySqlDialect()
	const params = (where: SQL | undefined) =>
		where ? dialect.sqlToQuery(where).params : []
	const canonical: Pick<EvergreenOfferJourneyTransaction, 'query'> = {
		query: {
			evergreenOfferJourneyCommit: {
				findFirst: async ({ where }) => {
					const p = params(where)
					calls.push(p.length === 1 ? `commit:${p[0]}` : `predecessor:${p[1]}`)
					return p.length === 1
						? commits.find((row) => row.stimulusId === p[0])
						: commits.find(
								(row) => row.journeyId === p[0] && row.actorVersion === p[1],
							)
				},
				findMany: async ({ where }) => {
					calls.push('settlements')
					const p = params(where)
					return commits.filter((row) => p.includes(row.stimulusId))
				},
			},
			evergreenOfferJourneyIntent: {
				findFirst: async ({ where }) =>
					allIntents.find((row) => row.idempotencyKey === params(where)[0]),
				findMany: async ({ where }) => {
					calls.push('normalized-intents')
					const p = params(where)
					return allIntents
						.filter(
							(row) => row.journeyId === p[0] && row.actorVersion === p[1],
						)
						.sort((a, b) => a.ordinal - b.ordinal)
				},
			},
			evergreenOfferJourneyWake: {
				findFirst: async ({ where }) =>
					allWakes.find((row) => row.wakeId === params(where)[0]),
				findMany: async ({ where }) => {
					calls.push('normalized-wakes')
					const p = params(where)
					return allWakes
						.filter(
							(row) => row.journeyId === p[0] && row.actorVersion === p[1],
						)
						.sort((a, b) => a.ordinal - b.ordinal)
				},
			},
		},
	}
	const store: VerifiedOwnerEvidenceReadStore = {
		canonical,
		intent: async (key) => {
			calls.push(`intent:${key}`)
			return key === intentRow.idempotencyKey ? intentRow : null
		},
		event: async (id) => {
			calls.push(`event:${id}`)
			return rows.find((row) => row.id === id) ?? null
		},
		identity: async (id) => {
			calls.push(`identity:${id}`)
			return id === identity.id ? identity : null
		},
	}
	return {
		secret,
		now,
		input,
		identity,
		login,
		claim,
		rows,
		commit,
		intentRow,
		store,
		calls,
		candidates,
		commits,
		allIntents,
		allWakes,
		issueIntent,
		bindIntent,
	}
}

function commitRow(
	candidate: JourneyLedgerCommit,
): typeof evergreenOfferJourneyCommit.$inferSelect {
	return {
		format: EVERGREEN_OFFER_JOURNEY_COMMIT_FORMAT,
		stimulusId: candidate.stimulus.stimulusId,
		journeyId: candidate.decision.next.journeyId,
		actorVersion: candidate.decision.next.version,
		admissionContactId:
			candidate.expectedVersion === null
				? candidate.decision.next.contactId
				: null,
		stimulusType: candidate.stimulus.type,
		commitEvidence: structuredClone(journeyCommitEvidenceRecord(candidate)),
		decision: structuredClone(candidate.decision),
		snapshot: JSON.parse(
			encodeEvergreenOfferJourneySnapshot(candidate.decision.next),
		),
		events: structuredClone(candidate.decision.events),
		receipt: structuredClone(candidate.decision.transitionReceipt),
		decidedAt: new Date(candidate.decidedAt),
		committedAt: new Date(candidate.decidedAt),
	}
}
function intentRows(
	candidate: JourneyLedgerCommit,
): (typeof evergreenOfferJourneyIntent.$inferSelect)[] {
	return candidate.decision.sideEffectIntents.map((intent, ordinal) => ({
		format: EVERGREEN_OFFER_JOURNEY_INTENT_FORMAT,
		idempotencyKey: intent.idempotencyKey,
		journeyId: intent.journeyId,
		originatingStimulusId: candidate.stimulus.stimulusId,
		actorVersion: candidate.decision.next.version,
		ordinal,
		intentType: intent.type,
		intent: structuredClone(intent),
		status: 'Pending',
		availableAt: new Date(
			intent.type === 'IssueCoupon'
				? intent.issueAt
				: intent.type === 'SendMessage'
					? intent.notBefore
					: candidate.decidedAt,
		),
		settledByStimulusId: null,
		settledAt: null,
		createdAt: new Date(candidate.decidedAt),
		updatedAt: new Date(candidate.decidedAt),
	}))
}
export const canonicalOriginProbes = [
	'empty-snapshot',
	'decision-ignored',
	'missing-bind-decision',
	'null-snapshot',
	'wrong-snapshot',
	'coupon-transplant',
	'actor50-without-previous',
	'source-reference-transplant',
	'receipt-evidence-version',
	'coherent-receipt-corruption',
	'joint-coupon-json-transplant',
	'missing-normalized-bind',
	'extra-normalized-wake',
] as const

/** Reviewer corruption probes, synthetic JSON only. Each starts from valid history. */
export function corruptCanonicalOrigin(
	f: ReturnType<typeof ownerProofFixture>,
	probe: (typeof canonicalOriginProbes)[number],
) {
	const object = (value: unknown): Record<string, unknown> => {
		if (!value || typeof value !== 'object' || Array.isArray(value))
			throw new Error('Bad probe fixture')
		return value as Record<string, unknown>
	}
	const item = (value: unknown): Record<string, unknown> => {
		if (!Array.isArray(value)) throw new Error('Bad probe array')
		return object(value[0])
	}
	const evidence = object(f.commit.commitEvidence)
	const decision = object(f.commit.decision)
	const receipt = object(f.commit.receipt)
	switch (probe) {
		case 'empty-snapshot':
			f.commit.snapshot = {}
			break
		case 'decision-ignored':
			f.commit.decision = { type: 'Ignored', reason: 'JourneyFinal' }
			f.commit.snapshot = null
			break
		case 'missing-bind-decision':
			decision.sideEffectIntents = []
			break
		case 'null-snapshot':
			f.commit.snapshot = null
			break
		case 'wrong-snapshot':
			object(object(f.commit.snapshot).aggregate).contactId = 'other-contact'
			break
		case 'coupon-transplant':
			f.input = { ...f.input, couponId: 'transplanted-coupon' }
			object(f.intentRow.intent).couponId = f.input.couponId
			object(item(f.commit.events).details).couponId = f.input.couponId
			decision.sideEffectIntents = []
			break
		case 'actor50-without-previous':
			f.commit.actorVersion = 50
			f.intentRow.actorVersion = 50
			evidence.expectedVersion = 49
			object(f.commit.snapshot).actorVersion = 50
			object(object(f.commit.snapshot).aggregate).version = 50
			object(decision.next).version = 50
			break
		case 'source-reference-transplant': {
			const id = 'transplanted-claim'
			f.rows[1]!.id = id
			f.intentRow.originatingStimulusId = id
			f.commit.stimulusId = id
			object(evidence.stimulus).stimulusId = id
			object(evidence.stimulus).sourceReference = claimSourceReference(id)
			receipt.stimulusId = id
			decision.sideEffectIntents = []
			break
		}
		case 'receipt-evidence-version':
			receipt.evidenceVersion = 'unrelated-evidence'
			break
		case 'coherent-receipt-corruption':
			receipt.evidenceVersion = 'unrelated-evidence'
			object(decision.transitionReceipt).evidenceVersion = 'unrelated-evidence'
			break
		case 'joint-coupon-json-transplant': {
			const id = 'transplanted-coupon'
			f.input = { ...f.input, couponId: id }
			object(f.intentRow.intent).couponId = id
			object(item(f.commit.events).details).couponId = id
			object(item(decision.events).details).couponId = id
			item(decision.sideEffectIntents).couponId = id
			object(object(decision.next).coupon).couponId = id
			object(object(object(f.commit.snapshot).aggregate).coupon).couponId = id
			break
		}
		case 'missing-normalized-bind':
			f.allIntents.splice(f.allIntents.indexOf(f.intentRow), 1)
			break
		case 'extra-normalized-wake':
			f.allWakes.push({
				...f.allWakes[0]!,
				originatingStimulusId: f.commit.stimulusId,
				actorVersion: f.commit.actorVersion,
				ordinal: 0,
			})
			break
	}
}

function wakeRows(
	candidate: JourneyLedgerCommit,
): (typeof evergreenOfferJourneyWake.$inferSelect)[] {
	return candidate.decision.wakeIntents.map((wake, ordinal) => ({
		format: EVERGREEN_OFFER_JOURNEY_WAKE_FORMAT,
		wakeId: wake.wakeId,
		journeyId: wake.journeyId,
		originatingStimulusId: candidate.stimulus.stimulusId,
		actorVersion: candidate.decision.next.version,
		ordinal,
		purposeType: wake.purpose.type,
		wake: structuredClone(wake),
		status: 'Pending',
		dueAt: new Date(wake.dueAt),
		settledByStimulusId: null,
		settledAt: null,
		createdAt: new Date(candidate.decidedAt),
		updatedAt: new Date(candidate.decidedAt),
	}))
}
