packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@sentry/cli': true
  '@swc/core': true
  better-sqlite3: true
  core-js: true
  esbuild: true
  msgpackr-extract: false
  msw: true
  nodemailer: true
  protobufjs: true
  sharp: true
  typesense-instantsearch-adapter: true
  unrs-resolver: true
  workerd: true

overrides:
  '@internationalized/date': '3.12.2'
  '@types/react': '19.2.7'
  '@types/react-dom': '19.2.3'

packageExtensions:
  '@coursebuilder/ui@*':
    dependencies:
      '@internationalized/date': '3.12.2'
