CREATE TABLE `AI_ContentRead` (
  `id` varchar(255) NOT NULL,
  `sessionId` varchar(255) NOT NULL,
  `contactId` varchar(255),
  `userId` varchar(255),
  `kitSubscriberId` varchar(255),
  `emailSha256` varchar(64),
  `contentId` varchar(255) NOT NULL,
  `contentSlug` varchar(255) NOT NULL,
  `contentType` varchar(100) NOT NULL,
  `parentSlug` varchar(255),
  `readSignal` varchar(50) NOT NULL,
  `sourceShortlinkSlug` varchar(50),
  `shortlinkMetadata` json,
  `firstTouch` json,
  `contentMetadata` json NOT NULL,
  `pathname` varchar(500) NOT NULL,
  `referrer` varchar(500),
  `userAgent` varchar(500),
  `country` varchar(2),
  `clientEventId` varchar(128) NOT NULL,
  `semanticIdempotencyKey` varchar(500) NOT NULL,
  `occurredAt` timestamp NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY (`id`),
  UNIQUE KEY `ContentRead_semanticIdempotencyKey_uq` (`semanticIdempotencyKey`),
  KEY `ContentRead_sessionId_idx` (`sessionId`),
  KEY `ContentRead_contactId_idx` (`contactId`),
  KEY `ContentRead_kitSubscriberId_idx` (`kitSubscriberId`),
  KEY `ContentRead_emailSha256_idx` (`emailSha256`),
  KEY `ContentRead_contentId_idx` (`contentId`),
  KEY `ContentRead_occurredAt_idx` (`occurredAt`),
  KEY `ContentRead_sourceShortlinkSlug_idx` (`sourceShortlinkSlug`)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COLLATE utf8mb4_0900_ai_ci;
